name: Update this VSCode extension.
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Python
        run: |
          set -x -e
          sudo apt install python3-setuptools
          python3 -m pip install --upgrade pip && pip3 install -r requirements.txt
      - name: Commit changes to Github
        run: |
          set -x -e
          git config --global user.name 'Github Actions'
          git config --global user.email 'danny@towardsthecloud.com'
          npm version minor --force --no-git-tag-version
          package_version=$(cat package.json|grep 'version":'|sed 's/[",]//g'|awk '{print $2}')
          git tag $package_version
          gitchangelog|tee "CHANGELOG.md"
          git commit -am "Changelog version: $package_version"
          git push
          git push origin --tags
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToVSCE
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.publishToVSCE.outputs.vsixPath }}
